/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as SystemRouteImport } from './routes/system'
import { Route as ReportCaseIdRouteImport } from './routes/report.$caseId'
import { Route as CaseCaseIdIndexRouteImport } from './routes/case.$caseId.index'
import { Route as CaseCaseIdRefusalRouteImport } from './routes/case.$caseId.refusal'
import { Route as CaseCaseIdWorkingRouteImport } from './routes/case.$caseId.working'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const SystemRoute = SystemRouteImport.update({
  id: '/system',
  path: '/system',
  getParentRoute: () => rootRouteImport,
} as any)
const ReportCaseIdRoute = ReportCaseIdRouteImport.update({
  id: '/report/$caseId',
  path: '/report/$caseId',
  getParentRoute: () => rootRouteImport,
} as any)
const CaseCaseIdIndexRoute = CaseCaseIdIndexRouteImport.update({
  id: '/case/$caseId/',
  path: '/case/$caseId/',
  getParentRoute: () => rootRouteImport,
} as any)
const CaseCaseIdRefusalRoute = CaseCaseIdRefusalRouteImport.update({
  id: '/case/$caseId/refusal',
  path: '/case/$caseId/refusal',
  getParentRoute: () => rootRouteImport,
} as any)
const CaseCaseIdWorkingRoute = CaseCaseIdWorkingRouteImport.update({
  id: '/case/$caseId/working',
  path: '/case/$caseId/working',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/system': typeof SystemRoute
  '/report/$caseId': typeof ReportCaseIdRoute
  '/case/$caseId/refusal': typeof CaseCaseIdRefusalRoute
  '/case/$caseId/working': typeof CaseCaseIdWorkingRoute
  '/case/$caseId/': typeof CaseCaseIdIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/system': typeof SystemRoute
  '/report/$caseId': typeof ReportCaseIdRoute
  '/case/$caseId/refusal': typeof CaseCaseIdRefusalRoute
  '/case/$caseId/working': typeof CaseCaseIdWorkingRoute
  '/case/$caseId': typeof CaseCaseIdIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/system': typeof SystemRoute
  '/report/$caseId': typeof ReportCaseIdRoute
  '/case/$caseId/refusal': typeof CaseCaseIdRefusalRoute
  '/case/$caseId/working': typeof CaseCaseIdWorkingRoute
  '/case/$caseId/': typeof CaseCaseIdIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/system'
    | '/report/$caseId'
    | '/case/$caseId/refusal'
    | '/case/$caseId/working'
    | '/case/$caseId/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/system'
    | '/report/$caseId'
    | '/case/$caseId/refusal'
    | '/case/$caseId/working'
    | '/case/$caseId'
  id:
    | '__root__'
    | '/'
    | '/system'
    | '/report/$caseId'
    | '/case/$caseId/refusal'
    | '/case/$caseId/working'
    | '/case/$caseId/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  SystemRoute: typeof SystemRoute
  ReportCaseIdRoute: typeof ReportCaseIdRoute
  CaseCaseIdRefusalRoute: typeof CaseCaseIdRefusalRoute
  CaseCaseIdWorkingRoute: typeof CaseCaseIdWorkingRoute
  CaseCaseIdIndexRoute: typeof CaseCaseIdIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/system': {
      id: '/system'
      path: '/system'
      fullPath: '/system'
      preLoaderRoute: typeof SystemRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/report/$caseId': {
      id: '/report/$caseId'
      path: '/report/$caseId'
      fullPath: '/report/$caseId'
      preLoaderRoute: typeof ReportCaseIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/case/$caseId/': {
      id: '/case/$caseId/'
      path: '/case/$caseId'
      fullPath: '/case/$caseId/'
      preLoaderRoute: typeof CaseCaseIdIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/case/$caseId/refusal': {
      id: '/case/$caseId/refusal'
      path: '/case/$caseId/refusal'
      fullPath: '/case/$caseId/refusal'
      preLoaderRoute: typeof CaseCaseIdRefusalRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/case/$caseId/working': {
      id: '/case/$caseId/working'
      path: '/case/$caseId/working'
      fullPath: '/case/$caseId/working'
      preLoaderRoute: typeof CaseCaseIdWorkingRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  SystemRoute: SystemRoute,
  ReportCaseIdRoute: ReportCaseIdRoute,
  CaseCaseIdRefusalRoute: CaseCaseIdRefusalRoute,
  CaseCaseIdWorkingRoute: CaseCaseIdWorkingRoute,
  CaseCaseIdIndexRoute: CaseCaseIdIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
